# Copyright 2021 guoqiao
# See LICENSE file for licensing details.
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  external-hostname:
    default: ""
    description: >
      The external hostname thsi application should be available on. If unset, it will default to the deployed
      application name in the model.
    type: string
  service-port:
    default: 8080
    description: on which port will naginx ingress expose the web ui.
    type: int
  webpassword:
    default: "pihole"
    description: set a secure password for pihole web, it will be random if blank.
    type: string
